name: CI
on: [pull_request]

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  automerge:
    needs: [test]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.6.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}